#!/bin/bash

for LINE in $(diskutil list | grep -E "Microsoft|Windows)
do
    PARTS=($LINE)
    echo "Found partition $PARTS[5] with label $PARTS[2]"
    echo "Try to unmount previous mount point..."
    diskutil umount $PARTS[5]
    echo "Mount it..."
    sudo mkdir /Volumes/$PARTS[2]
    sudo /usr/local/sbin/mount_ntfs /dev/$PARTS[5] /Volumes/$PARTS[2]
done
