#!/bin/bash

for LINE in $(diskutil list | grep -E "Microsoft|Windows)
do
    PARTS=($LINE)
    echo "Found partition $PARTS[5] with label $PARTS[2]"
    echo "Unmount it..."
    diskutil umount $PARTS[5]
	sudo rmdir /Volumes/$PARTS[2]
done
